apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-rolling-update
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
        role: rolling-update
    spec:
      containers:
      - name: myContainer
        image: asantosnav/capstone
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

