apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-rolling-update
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: capstone
        role: rolling-update
    spec:
      containers:
      - name: capstone
        image: asantosnav/capstone
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUp      maxSurge: 50%