apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-rolling-update
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
        role: rolling-update
    spec:
      containers:
      - name: capstone
        image: asantosnav/capstone
        ports:
        - containerPort: 80
        #readinessProbe:
         # httpGet:
          #  path: /
           # port: 80
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

#apiVersion: v1
#kind: Service
#metadata:
 # name: capstone-expose
  #labels:
   # app: capstone
#spec:
 # type: LoadBalancer
  #selector:
   # app: capstone
  #ports:
   # - protocol: TCP
    #  port: 80
     # targetPort: 80